import ROOT
from CMGTools.BKstLL.analyzers.L1PurityTreeProducerBase import L1PurityTreeProducerBase
from CMGTools.BKstLL.analyzers.L1Seeds import single_muon, di_muon, tri_muon
from PhysicsTools.HeppyCore.utils.deltar import deltaR, deltaPhi
from itertools import combinations

class BKstLLGenTreeProducer(L1PurityTreeProducerBase):

    '''
    '''

    def declareVariables(self, setup):
        '''
        '''
        self.bookEvent(self.tree)

        # gen pt hat
        #self.var(self.tree, 'qscale')
        
        # gen tagging muon
        self.bookGenParticle(self.tree, 'tag_mu')
        self.bookParticle   (self.tree, 'tag_mu_reco')
                
        # gen level B mesons from the hard interaction, sorted by pt
        self.var(self.tree, 'nbmesons')
        
        self.bookGenParticle(self.tree, 'bd')

        self.bookGenParticle(self.tree, 'b1')
        self.bookGenParticle(self.tree, 'b2')
        self.bookGenParticle(self.tree, 'b3')

        self.bookJet(self.tree, 'b1_jet', fill_extra=True)
        self.bookJet(self.tree, 'b2_jet', fill_extra=True)
        self.bookJet(self.tree, 'b3_jet', fill_extra=True)

        # bbbar topology
        self.var(self.tree, 'dr_btag_bprobe'   )
        self.var(self.tree, 'deta_btag_bprobe' )
        self.var(self.tree, 'dphi_btag_bprobe' )
        self.var(self.tree, 'dr_mutag_bprobe'  )
        self.var(self.tree, 'deta_mutag_bprobe')
        self.var(self.tree, 'dphi_mutag_bprobe')

        # first two gen level muons from B mesons, sorted by pt
        self.bookGenParticle(self.tree, 'bd_lp') ; self.bookParticle(self.tree, 'bd_lp_reco')
        self.bookGenParticle(self.tree, 'bd_lm') ; self.bookParticle(self.tree, 'bd_lm_reco')
        self.bookGenParticle(self.tree, 'bd_pi') ; self.bookParticle(self.tree, 'bd_pi_reco')
        self.bookGenParticle(self.tree, 'bd_k' ) ; self.bookParticle(self.tree, 'bd_k_reco' )
        self.bookJet(self.tree, 'bd_jet', fill_extra=True)
        self.var(self.tree, 'bd_dr' )

        # L1 seeds. Bool, either fired or not
        self.var(self.tree, 'L1_SingleMu_7p0_eta2p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_7p5_eta2p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_8p0_eta2p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_8p5_eta2p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_9p0_eta2p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_9p5_eta2p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_10p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_10p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_11p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_11p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_12p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_12p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_13p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_13p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_14p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_14p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_15p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_15p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_16p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_16p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_17p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_17p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_18p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_18p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_19p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_19p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_20p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_20p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_21p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_21p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_22p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_22p5_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_23p0_eta2p5_Q12')
        self.var(self.tree, 'L1_SingleMu_7p0_eta2p1_Q12' )
        self.var(self.tree, 'L1_SingleMu_7p5_eta2p1_Q12' )
        self.var(self.tree, 'L1_SingleMu_8p0_eta2p1_Q12' )
        self.var(self.tree, 'L1_SingleMu_8p5_eta2p1_Q12' )
        self.var(self.tree, 'L1_SingleMu_9p0_eta2p1_Q12' )
        self.var(self.tree, 'L1_SingleMu_9p5_eta2p1_Q12' )
        self.var(self.tree, 'L1_SingleMu_10p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_10p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_11p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_11p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_12p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_12p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_13p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_13p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_14p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_14p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_15p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_15p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_16p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_16p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_17p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_17p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_18p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_18p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_19p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_19p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_20p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_20p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_21p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_21p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_22p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_22p5_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_23p0_eta2p1_Q12')
        self.var(self.tree, 'L1_SingleMu_7p0_eta1p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_7p5_eta1p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_8p0_eta1p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_8p5_eta1p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_9p0_eta1p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_9p5_eta1p5_Q12' )
        self.var(self.tree, 'L1_SingleMu_10p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_10p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_11p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_11p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_12p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_12p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_13p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_13p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_14p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_14p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_15p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_15p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_16p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_16p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_17p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_17p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_18p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_18p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_19p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_19p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_20p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_20p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_21p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_21p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_22p0_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_22p5_eta1p5_Q12')
        self.var(self.tree, 'L1_SingleMu_23p0_eta1p5_Q12')

#         self.var(self.tree, 'L1_SingleMu_22_eta2p1_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_25_Q12'                 )
#         self.var(self.tree, 'L1_SingleMu_25_eta1p0_Q12'          )
#   
#         self.var(self.tree, 'L1_SingleMu_7_eta0p5_Q8'            )
#         self.var(self.tree, 'L1_SingleMu_7_eta0p5_Q12'           )
#         self.var(self.tree, 'L1_SingleMu_7_eta0p8_Q8'            )
#         self.var(self.tree, 'L1_SingleMu_7_eta0p8_Q12'           )
#         self.var(self.tree, 'L1_SingleMu_7_eta1p0_Q8'            )
#         self.var(self.tree, 'L1_SingleMu_7_eta1p0_Q12'           )
#         self.var(self.tree, 'L1_SingleMu_7_eta1p5_Q8'            )
#         self.var(self.tree, 'L1_SingleMu_7_eta1p5_Q12'           )
#         self.var(self.tree, 'L1_SingleMu_7_eta2p1_Q8'            )
#         self.var(self.tree, 'L1_SingleMu_7_eta2p1_Q12'           )
#         self.var(self.tree, 'L1_SingleMu_7_eta2p5_Q8'            )
#         self.var(self.tree, 'L1_SingleMu_7_eta2p5_Q12'           )
#   
#         self.var(self.tree, 'L1_SingleMu_10_eta0p5_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_10_eta0p5_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_10_eta0p8_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_10_eta0p8_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_10_eta1p0_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_10_eta1p0_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_10_eta1p5_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_10_eta1p5_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_10_eta2p1_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_10_eta2p1_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_10_eta2p5_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_10_eta2p5_Q12'          )
# 
#         self.var(self.tree, 'L1_SingleMu_12_eta0p5_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_12_eta0p5_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_12_eta0p8_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_12_eta0p8_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_12_eta1p0_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_12_eta1p0_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_12_eta1p5_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_12_eta1p5_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_12_eta2p1_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_12_eta2p1_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_12_eta2p5_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_12_eta2p5_Q12'          )
#   
#         self.var(self.tree, 'L1_SingleMu_15_eta0p5_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_15_eta0p5_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_15_eta0p8_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_15_eta0p8_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_15_eta1p0_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_15_eta1p0_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_15_eta1p5_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_15_eta1p5_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_15_eta2p1_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_15_eta2p1_Q12'          )
#         self.var(self.tree, 'L1_SingleMu_15_eta2p5_Q8'           )
#         self.var(self.tree, 'L1_SingleMu_15_eta2p5_Q12'          )
#   
#         self.var(self.tree, 'L1_DoubleMu_15_7_Q8'                )
#         self.var(self.tree, 'L1_DoubleMu0er1p5_SQ_OS_dR_Max1p4'  )
#         self.var(self.tree, 'L1_DoubleMu4_SQ_OS_dR_Max1p2'       )
#         self.var(self.tree, 'L1_DoubleMu4p5_SQ_OS_dR_Max1p2'     )
#         self.var(self.tree, 'L1_DoubleMu5_3er2p1_SQ_OS_dR_Max1p4')

        # is the given L1 seed fired by one B meson?
        self.var(self.tree, 'matched_L1_SingleMu_7p0_eta2p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_7p5_eta2p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_8p0_eta2p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_8p5_eta2p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_9p0_eta2p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_9p5_eta2p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_10p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_10p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_11p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_11p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_12p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_12p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_13p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_13p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_14p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_14p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_15p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_15p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_16p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_16p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_17p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_17p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_18p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_18p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_19p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_19p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_20p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_20p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_21p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_21p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_22p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_22p5_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_23p0_eta2p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_7p0_eta2p1_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_7p5_eta2p1_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_8p0_eta2p1_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_8p5_eta2p1_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_9p0_eta2p1_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_9p5_eta2p1_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_10p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_10p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_11p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_11p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_12p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_12p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_13p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_13p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_14p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_14p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_15p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_15p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_16p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_16p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_17p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_17p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_18p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_18p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_19p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_19p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_20p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_20p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_21p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_21p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_22p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_22p5_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_23p0_eta2p1_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_7p0_eta1p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_7p5_eta1p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_8p0_eta1p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_8p5_eta1p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_9p0_eta1p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_9p5_eta1p5_Q12' )
        self.var(self.tree, 'matched_L1_SingleMu_10p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_10p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_11p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_11p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_12p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_12p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_13p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_13p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_14p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_14p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_15p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_15p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_16p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_16p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_17p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_17p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_18p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_18p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_19p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_19p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_20p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_20p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_21p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_21p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_22p0_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_22p5_eta1p5_Q12')
        self.var(self.tree, 'matched_L1_SingleMu_23p0_eta1p5_Q12')

#         self.var(self.tree, 'matched_L1_SingleMu_22_eta2p1_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_25_Q12'                 )
#         self.var(self.tree, 'matched_L1_SingleMu_25_eta1p0_Q12'          )
#   
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta0p5_Q8'            )
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta0p5_Q12'           )
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta0p8_Q8'            )
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta0p8_Q12'           )
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta1p0_Q8'            )
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta1p0_Q12'           )
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta1p5_Q8'            )
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta1p5_Q12'           )
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta2p1_Q8'            )
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta2p1_Q12'           )
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta2p5_Q8'            )
#         self.var(self.tree, 'matched_L1_SingleMu_7_eta2p5_Q12'           )
#   
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta0p5_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta0p5_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta0p8_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta0p8_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta1p0_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta1p0_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta1p5_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta1p5_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta2p1_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta2p1_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta2p5_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_10_eta2p5_Q12'          )
# 
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta0p5_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta0p5_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta0p8_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta0p8_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta1p0_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta1p0_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta1p5_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta1p5_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta2p1_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta2p1_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta2p5_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_12_eta2p5_Q12'          )
#   
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta0p5_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta0p5_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta0p8_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta0p8_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta1p0_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta1p0_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta1p5_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta1p5_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta2p1_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta2p1_Q12'          )
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta2p5_Q8'           )
#         self.var(self.tree, 'matched_L1_SingleMu_15_eta2p5_Q12'          )
#   
#         self.var(self.tree, 'matched_L1_DoubleMu_15_7_Q8'                )
#         self.var(self.tree, 'matched_L1_DoubleMu0er1p5_SQ_OS_dR_Max1p4'  )
#         self.var(self.tree, 'matched_L1_DoubleMu4_SQ_OS_dR_Max1p2'       )
#         self.var(self.tree, 'matched_L1_DoubleMu4p5_SQ_OS_dR_Max1p2'     )
#         self.var(self.tree, 'matched_L1_DoubleMu5_3er2p1_SQ_OS_dR_Max1p4')

    def process(self, event):
        '''
        '''
        self.readCollections(event.input)
        self.tree.reset()

        if not eval(self.skimFunction):
            return False

        self.fillEvent(self.tree, event)
        #self.fill(self.tree, 'qscale', event.qscale)
        
        self.fill(self.tree, 'nbmesons', len(event.gen_bmesons))

        # gen tagging muon
        if hasattr(event, 'thetagmu'):
            self.fillGenParticle(self.tree, 'tag_mu', event.thetagmu)
            if hasattr(event.thetagmu, 'reco'):
                self.fillParticle(self.tree, 'tag_mu_reco', event.thetagmu.reco)

        self.fillGenParticle(self.tree, 'bd', event.kstll)
        self.fill(self.tree, 'bd_dr', event.kstll.dr)

        #for jet in event.jets:
        #    if deltaR(event.kstll, jet) < 0.4:
        #        self.fillJet(self.tree, 'bd_jet', jet, fill_extra=True)

        self.fillGenParticle(self.tree, 'bd_lp', event.kstll.lp)
                
        if hasattr(event.kstll.lp, 'reco'):
            self.fillParticle(self.tree, 'bd_lp_reco', event.kstll.lp.reco)       
        self.fillGenParticle(self.tree, 'bd_lm', event.kstll.lm)
        if hasattr(event.kstll.lm, 'reco'):
            self.fillParticle(self.tree, 'bd_lm_reco', event.kstll.lm.reco)
        self.fillGenParticle(self.tree, 'bd_pi', event.kstll.pi)
        if hasattr(event.kstll.pi, 'reco'):
            self.fillParticle(self.tree, 'bd_pi_reco', event.kstll.pi.reco)
        self.fillGenParticle(self.tree, 'bd_k' , event.kstll.k )
        if hasattr(event.kstll.k, 'reco'):
            self.fillParticle(self.tree, 'bd_k_reco', event.kstll.k.reco)

        for i, ib in enumerate(event.clean_gen_bmesons[:3]):
            self.fillGenParticle(self.tree, 'b%d' %(i+1), ib)
            #for jet in event.jets:
                #if deltaR(ib, jet) < 0.4:
                    #self.fillJet(self.tree, 'b%d_jet' %(i+1), jet, fill_extra=True)

        if len(event.clean_gen_bmesons)>0:
            self.fill(self.tree, 'dr_btag_bprobe'   , deltaR  (event.clean_gen_bmesons[0], event.kstll)             )
            self.fill(self.tree, 'deta_btag_bprobe' , abs     (event.clean_gen_bmesons[0].eta() - event.kstll.eta()))
            self.fill(self.tree, 'dphi_btag_bprobe' , deltaPhi(event.clean_gen_bmesons[0].phi(), event.kstll.phi()) )
        if hasattr(event, 'thetagmu'):
            self.fill(self.tree, 'dr_mutag_bprobe'  , deltaR  (event.thetagmu, event.kstll)                         )
            self.fill(self.tree, 'deta_mutag_bprobe', abs     (event.thetagmu.eta() - event.kstll.eta())            )
            self.fill(self.tree, 'dphi_mutag_bprobe', deltaPhi(event.thetagmu.phi(), event.kstll.phi())             )


        fired, matched, index = single_muon(event.L1_muons, 7.0 , 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7p0_eta2p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7p0_eta2p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 7.5 , 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7p5_eta2p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7p5_eta2p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 8.0 , 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_8p0_eta2p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_8p0_eta2p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 8.5 , 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_8p5_eta2p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_8p5_eta2p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 9.0 , 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_9p0_eta2p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_9p0_eta2p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 9.5 , 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_9p5_eta2p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_9p5_eta2p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 10.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 10.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 11.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_11p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_11p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 11.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_11p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_11p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 12.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 12.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 13.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_13p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_13p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 13.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_13p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_13p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 14.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_14p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_14p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 14.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_14p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_14p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 15.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 15.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 16.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_16p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_16p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 16.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_16p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_16p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 17.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_17p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_17p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 17.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_17p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_17p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 18.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_18p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_18p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 18.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_18p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_18p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 19.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_19p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_19p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 19.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_19p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_19p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 20.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_20p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_20p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 20.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_20p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_20p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 21.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_21p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_21p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 21.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_21p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_21p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 22.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_22p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_22p0_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 22.5, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_22p5_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_22p5_eta2p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 23.0, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_23p0_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_23p0_eta2p5_Q12', int(matched) * (index+1))

        fired, matched, index = single_muon(event.L1_muons, 7.0 , 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7p0_eta2p1_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7p0_eta2p1_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 7.5 , 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7p5_eta2p1_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7p5_eta2p1_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 8.0 , 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_8p0_eta2p1_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_8p0_eta2p1_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 8.5 , 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_8p5_eta2p1_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_8p5_eta2p1_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 9.0 , 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_9p0_eta2p1_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_9p0_eta2p1_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 9.5 , 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_9p5_eta2p1_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_9p5_eta2p1_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 10.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 10.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 11.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_11p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_11p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 11.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_11p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_11p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 12.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 12.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 13.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_13p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_13p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 13.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_13p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_13p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 14.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_14p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_14p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 14.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_14p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_14p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 15.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 15.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 16.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_16p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_16p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 16.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_16p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_16p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 17.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_17p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_17p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 17.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_17p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_17p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 18.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_18p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_18p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 18.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_18p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_18p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 19.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_19p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_19p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 19.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_19p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_19p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 20.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_20p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_20p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 20.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_20p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_20p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 21.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_21p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_21p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 21.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_21p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_21p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 22.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_22p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_22p0_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 22.5, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_22p5_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_22p5_eta2p1_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 23.0, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_23p0_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_23p0_eta2p1_Q12', int(matched) * (index+1))

        fired, matched, index = single_muon(event.L1_muons, 7.0 , 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7p0_eta1p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7p0_eta1p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 7.5 , 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7p5_eta1p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7p5_eta1p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 8.0 , 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_8p0_eta1p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_8p0_eta1p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 8.5 , 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_8p5_eta1p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_8p5_eta1p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 9.0 , 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_9p0_eta1p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_9p0_eta1p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 9.5 , 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_9p5_eta1p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_9p5_eta1p5_Q12' , int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 10.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 10.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 11.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_11p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_11p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 11.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_11p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_11p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 12.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 12.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 13.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_13p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_13p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 13.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_13p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_13p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 14.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_14p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_14p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 14.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_14p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_14p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 15.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 15.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 16.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_16p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_16p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 16.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_16p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_16p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 17.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_17p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_17p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 17.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_17p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_17p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 18.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_18p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_18p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 18.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_18p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_18p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 19.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_19p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_19p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 19.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_19p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_19p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 20.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_20p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_20p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 20.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_20p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_20p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 21.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_21p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_21p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 21.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_21p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_21p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 22.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_22p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_22p0_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 22.5, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_22p5_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_22p5_eta1p5_Q12', int(matched) * (index+1))
        fired, matched, index = single_muon(event.L1_muons, 23.0, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_23p0_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_23p0_eta1p5_Q12', int(matched) * (index+1))





                        
#         fired, matched, index = single_muon(event.L1_muons, 22, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_22_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_22_eta2p1_Q12', int(matched) * (index+1))
#         
#         fired, matched, index = single_muon(event.L1_muons, 25, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_25_Q12'       , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_25_Q12'       , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 25, 1.0, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_25_eta1p0_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_25_eta1p0_Q12', int(matched) * (index+1))
# 
#         fired, matched, index = single_muon(event.L1_muons,  7, 0.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta0p5_Q8'  , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta0p5_Q8'  , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons,  7, 0.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta0p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta0p5_Q12' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons,  7, 0.8,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta0p8_Q8'  , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta0p8_Q8'  , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons,  7, 0.8, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta0p8_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta0p8_Q12' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons,  7, 1.0,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta1p0_Q8'  , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta1p0_Q8'  , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons,  7, 1.0, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta1p0_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta1p0_Q12' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons,  7, 1.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta1p5_Q8'  , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta1p5_Q8'  , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons,  7, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta1p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta1p5_Q12' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons,  7, 2.1,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta2p1_Q8'  , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta2p1_Q8'  , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons,  7, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta2p1_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta2p1_Q12' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons,  7, 2.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta2p5_Q8'  , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta2p5_Q8'  , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons,  7, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_7_eta2p5_Q12' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_7_eta2p5_Q12' , int(matched) * (index+1))
# 
#         fired, matched, index = single_muon(event.L1_muons, 10, 0.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta0p5_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta0p5_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 10, 0.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta0p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta0p5_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 10, 0.8,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta0p8_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta0p8_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 10, 0.8, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta0p8_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta0p8_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 10, 1.0,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta1p0_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta1p0_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 10, 1.0, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta1p0_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta1p0_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 10, 1.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta1p5_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta1p5_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 10, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta1p5_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 10, 2.1,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta2p1_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta2p1_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 10, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta2p1_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 10, 2.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta2p5_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta2p5_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 10, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_10_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_10_eta2p5_Q12', int(matched) * (index+1))
# 
#         fired, matched, index = single_muon(event.L1_muons, 12, 0.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta0p5_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta0p5_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 12, 0.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta0p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta0p5_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 12, 0.8,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta0p8_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta0p8_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 12, 0.8, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta0p8_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta0p8_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 12, 1.0,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta1p0_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta1p0_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 12, 1.0, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta1p0_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta1p0_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 12, 1.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta1p5_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta1p5_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 12, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta1p5_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 12, 2.1,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta2p1_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta2p1_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 12, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta2p1_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 12, 2.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta2p5_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta2p5_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 12, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_12_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_12_eta2p5_Q12', int(matched) * (index+1))
# 
#         fired, matched, index = single_muon(event.L1_muons, 15, 0.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta0p5_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta0p5_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 15, 0.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta0p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta0p5_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 15, 0.8,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta0p8_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta0p8_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 15, 0.8, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta0p8_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta0p8_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 15, 1.0,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta1p0_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta1p0_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 15, 1.0, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta1p0_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta1p0_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 15, 1.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta1p5_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta1p5_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 15, 1.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta1p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta1p5_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 15, 2.1,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta2p1_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta2p1_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 15, 2.1, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta2p1_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta2p1_Q12', int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 15, 2.5,  8, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta2p5_Q8' , fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta2p5_Q8' , int(matched) * (index+1))
#         fired, matched, index = single_muon(event.L1_muons, 15, 2.5, 12, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_SingleMu_15_eta2p5_Q12', fired) ; self.fill(self.tree, 'matched_L1_SingleMu_15_eta2p5_Q12', int(matched) * (index+1))
# 
#         fired, matched, index = di_muon    (event.L1_muons, 15  , 7  , qual1= 8, qual2= 8, matches=event.clean_gen_bmesons);                                        self.fill(self.tree, 'L1_DoubleMu_15_7_Q8'                , fired) ; self.fill(self.tree, 'matched_L1_DoubleMu_15_7_Q8'                , int(matched) * (index+1))
#         fired, matched, index = di_muon    (event.L1_muons,  0  , 0  , eta1=1.5, eta2=1.5, qual1=12, qual2=12, maxDr=1.4, sign=0, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_DoubleMu0er1p5_SQ_OS_dR_Max1p4'  , fired) ; self.fill(self.tree, 'matched_L1_DoubleMu0er1p5_SQ_OS_dR_Max1p4'  , int(matched) * (index+1))
#         fired, matched, index = di_muon    (event.L1_muons,  4  , 4  , qual1=12, qual2=12, maxDr=1.2, sign=0, matches=event.clean_gen_bmesons);                     self.fill(self.tree, 'L1_DoubleMu4_SQ_OS_dR_Max1p2'       , fired) ; self.fill(self.tree, 'matched_L1_DoubleMu4_SQ_OS_dR_Max1p2'       , int(matched) * (index+1))
#         fired, matched, index = di_muon    (event.L1_muons,  4.5, 4.5, qual1=12, qual2=12, maxDr=1.2, sign=0, matches=event.clean_gen_bmesons);                     self.fill(self.tree, 'L1_DoubleMu4p5_SQ_OS_dR_Max1p2'     , fired) ; self.fill(self.tree, 'matched_L1_DoubleMu4p5_SQ_OS_dR_Max1p2'     , int(matched) * (index+1))
#         fired, matched, index = di_muon    (event.L1_muons,  5  , 3  , eta1=2.1, eta2=2.1, qual1=12, qual2=12, maxDr=1.4, sign=0, matches=event.clean_gen_bmesons); self.fill(self.tree, 'L1_DoubleMu5_3er2p1_SQ_OS_dR_Max1p4', fired) ; self.fill(self.tree, 'matched_L1_DoubleMu5_3er2p1_SQ_OS_dR_Max1p4', int(matched) * (index+1))
        
        self.fillTree(event)


